### ISSUE TITLE
Git submodule update failed

### ISSUE THREAD

**Issue by iWeslie** [diogot/MyWeight#128]
After I have finished `brew install...`. I meet an error while running `git submodule update --init --recursive`     
Here is the ERROR output.How can I resolve it?    
```
Submodule 'rakelib' (git@github.com:diogot/xcode-rakelib.git) registered for path 'rakelib'
Cloning into '/Users/weslie/Desktop/XCode/ProjectForReference/watchOS/MyWeight/rakelib'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:diogot/xcode-rakelib.git' into submodule path '/Users/weslie/Desktop/XCode/ProjectForReference/watchOS/MyWeight/rakelib' failed
Failed to clone 'rakelib'. Retry scheduled
Cloning into '/Users/weslie/Desktop/XCode/ProjectForReference/watchOS/MyWeight/rakelib'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:diogot/xcode-rakelib.git' into submodule path '/Users/weslie/Desktop/XCode/ProjectForReference/watchOS/MyWeight/rakelib' failed
Failed to clone 'rakelib' a second time, aborting
```

**Comment by diogot** [comment]
It looks like you're trying to clone the repository using ssh, but you don't have an ssh key.

**Comment by iWeslie** [comment]
Finally, I have successfully built the project 😄 It almost cost me half a day.          
I am using `Xcode9`,one may will probably have some errors to install the dependencies. **ALL ERRORS** I have met are concluded below for references.    
> git submodule update --init --recursive      

missing SSH key       
#### add the ssh key  -> <https://github.com/settings/keys>
    
- - -

> bundle install    

The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Your Ruby version is 2.0.0, but your Gemfile specified 2.4.1
    
```
$ gem update bundler
$ bundle install
```
    
- - -

##### Gemfile -> `bundle install`    
##### Podfile -> `pod install`

`$ rake setup` may not always work. Try `$ bundle install` could work with the project.

**Comment by diogot** [comment]
I'll update the documentation and the project to Xcode 9 soon.
Thanks!
