### ISSUE TITLE
Apple Watch complication

### ISSUE THREAD

**Issue by brunokoga** [diogot/MyWeight#129]
According to the [WatchKit Programming Guide](https://developer.apple.com/library/content/documentation/General/Conceptual/WatchKitProgrammingGuide/index.html), _Apple recommends that all Watch apps include a complication, even if that complication only acts as a button to launch the app_.

Besides that, I think a good action for the complication (at least for me 😅) would be to open the app directly in the input screen.

**Comment by marcelmueller** [comment]
That would be awesome. I'll gladly provide the assets. 😄

**Comment by diogot** [comment]
🎉

**Comment by marcelmueller** [comment]
Are we using Stack or Simple? I feel like Stack could be nice if we provide the latest input. 
(https://developer.apple.com/watchos/human-interface-guidelines/app-architecture/complications/)

**Comment by brunokoga** [comment]
I honestly don't have a strong opinion on this one. _For me_, simple would be more than enough, but I guess it wouldn't harm to have the latest input shown.

**Comment by diogot** [comment]
I have mixed feelings about being able to look my weight all the time. I'm worried about let the user anxious.

**Comment by diogot** [comment]
Although would be interesting if the stack showed the time since the last measure.

**Comment by marcelmueller** [comment]
Yeah, it's a good point. I'm not sure if showing last time would be clear enough for the person to understand what is it about. Maybe we can start with something real simple, haha.

**Comment by brunokoga** [comment]
Let's do the `simple` then (yay!).

**Comment by marcelmueller** [comment]
Alright! I'll make sure to provide assets. 😄
