### ISSUE TITLE
Features wanted for version 1.0

### ISSUE THREAD

**Issue by diogot** [diogot/MyWeight#4]
What do we want for version 1.0?

**Comment by brunokoga** [comment]
For 1.0 we want the bare minimum.

Here are the things I think it's important for an early version (not necessarily 1.0):

- A nice way to tell the user that we will need permission to access and write to Health data;
- If the user hasn't given permission, we need to gracefully handle that. We also need to make it easy for the user to give permission later (maybe a Settings screen?);
- A way for the user to be reminded to add his daily weight measurement;
- A very simple and straightforward way to input new data;
- A way to visualize all the data;
- A way to edit and delete data;
- Watch app to add the daily weight measurement.

Is there anything else I'm missing? I think we can start the discussion from this list now :)

**Comment by diogot** [comment]
I agree with most of the points, I just would let the reminder for a further version.
Also I don't think that edit an existent data point should be allowed, but deletions should be ok.

The interactions should be:

- iPhone app
	- Health data access permission
	- Data input
	- Data view
	- Data deletion
	
- Watch App
	- Health data access permission
	- Data input

The central point is data storage, and I think it should be a first point of discussion.
Once we close this point we should move to have drafts of the interactions following implementations. Make sense?

I create an issue for data storage #9

**Comment by diogot** [comment]
Updates:

- iPhone app
	- Health data access permission
	- Data input
	- Data view

We'll drop data deletion and watch in this first version.
