### ISSUE TITLE
Tests? 

### ISSUE THREAD

**Issue by BrunoMazzo** [diogot/MyWeight#68]
You are not using Cocoapods, so the tests will be done on XCTest? Or can I install other framework to help? Like Quick and Nimble?

**Comment by diogot** [comment]
That's a hard one. We're trying to go no libs for now.
Although Quick/Nimble are just libs for tests.
I thinks that's fair to use CocoaPods for Quick/Nimble.
Take a look on the rake tasks for project setup :-)
