### ISSUE TITLE
Layout glitches

### ISSUE THREAD

**Issue by igorcferreira** [diogot/MyWeight#73]
**Problem**

```
On some states, especially after rotation of device, the layout present glitches like button size, top spacing and missing texts.
```

**System**

```
- Device: iPhone 7+ (MN4M2B/A)
- iOS: 10.2 (14C5062e)
- App version: 1.0 (3)
```

**Detailed cases**

* New Entry View

- [x] Weird top space on the screen to add new entry [(portrait)](https://cloud.githubusercontent.com/assets/2117340/20033184/376f62aa-a393-11e6-9b82-09ea5703c93f.PNG) 
- [ ] New entry view title missing on [landscape](https://cloud.githubusercontent.com/assets/2117340/20033208/c5e9fab8-a393-11e6-8d60-afe8ccf53f92.PNG)
- [ ] After rotation, the save button on new entry changes its side [(portrait)](https://cloud.githubusercontent.com/assets/2117340/20033229/017ba69e-a394-11e6-805d-f25a9325747d.PNG)
- [ ] After rotation, the save button disappears from the layout [(landscape)](https://cloud.githubusercontent.com/assets/2117340/20033238/28721c2e-a394-11e6-9ceb-92c1b3594585.PNG)

* Entries list view

- [x] Entry list appearing behind `Add` button [(portrait)](https://cloud.githubusercontent.com/assets/2117340/20033202/993d09ce-a393-11e6-9a78-5a8f750b5c6b.PNG)

**Comment by BrunoMazzo** [comment]
The `AddViewController` layout is ambiguous on portrait.
I don't think is possible to use one picker on top of the other on portrait at smaller devices. Maybe you should change for side by side on these cases?

**Comment by diogot** [comment]
Thanks for the report :-)

- We didn't designed for landscape use, maybe is better to lock for portrait only.
What do you think @marcelmueller ?

- The weird top will be solved when the final design were implemented:
<img width="361" alt="screen shot 2016-11-05 at 22 28 34" src="https://cloud.githubusercontent.com/assets/885516/20035559/477644e8-a3a7-11e6-9f9a-d9e4d40244cf.png">

- The weight list behind the button will also be solved with the final design:
<img width="242" alt="screen shot 2016-11-05 at 22 31 19" src="https://cloud.githubusercontent.com/assets/885516/20035566/99e8d4fc-a3a7-11e6-9191-ba3ca2ab36c3.png">

**Comment by marcelmueller** [comment]
As Diogo said, the app wasn't designed to work on landscape – we were planning to add some kind of data visualization whenever the device entered that mode, but that's definitely not meant for the first release.

I agree with locking the orientation. 😄

As for the other items, Diogo already showed the final designs! 👍
