### ISSUE TITLE
Include the possibility to edit value for entry

### ISSUE THREAD

**Issue by igorcferreira** [diogot/MyWeight#94]
I don't know if it is possible, but, it would be great to have the possibility to edit an entry. So, if happens that the user added the wrong value, or re measured a saw divergence, it can fix it.

**Comment by diogot** [comment]
It's not possible to edit an entry on HealthKit, but a delete feature is possible.

**Comment by BrunoMazzo** [comment]
In some systems, update is a delete plus a insert. If it's fast, it's invisible to the user.

**Comment by diogot** [comment]
You got a point

**Comment by diogot** [comment]
We can delete since #98
